### PR TITLE
Adding Dart Snippets

### PR DESCRIPTION
**Pull request by rakarmp**
I have added folders and files:

*Dart
     └── dart_snippets.md

I think for darts this is very useful because we know ourselves before going to flutter it's good to learn darts first.

### CODE REVIEW

**Review by RaymonDev — CHANGES_REQUESTED** [review]
Can you add each ## into separate files like the HTML section or the R section?

**Comment by rakarmp** [comment]
> Can you add each ## into separate files like the HTML section or the R section?

of course you can, I'll make changes right away

**Comment by RaymonDev** [comment]
Cool!! Text me when it's done and I will merge it!!

**Comment by rakarmp** [comment]
> Cool!! Text me when it's done and I will merge it!!

I have made the changes as you requested

**Comment by RaymonDev** [comment]
That is awesome, you just earned yourself a new follower :) 

Thank you so much!!!

**Comment by rakarmp** [comment]
> That is awesome, you just earned yourself a new follower :)
> 
> Thank you so much!!!

no problem, I'm happy to contribute to your project.

**Pull request merged**
